### ISSUE TITLE
Migration Checklist

### ISSUE THREAD

**Issue by etekweb** [etekweb/etekweb-iles#7]
- [x] Confirm working production build
- [x] Set up deployment to Cloudflare Pages
- [ ] Feature parity with previous site ([see relevant issues here](https://github.com/etekweb/etekweb-iles/issues?q=is%3Aopen+is%3Aissue+label%3A%22works+on+old+site%22))
- [x] Move legacy static HTML files over to new repo
- [x] Set up Cloudflare DNS for domain
- [x] Set up temporary subdomain next.etekweb.net
- [x] Add banner to old site pointing to new site
- [x] Enable Cloudflare proxy features
- [x] Change DNS settings to point etekweb.net to new site
- [x] Redirect next.etekweb.net to etekweb.net
- [x] Set up heyethan.dev
- [ ] Archive old repo
- [ ] Rename new repo to etekweb.net (optional)
